name: Master

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --prefer-offline
      - name: Create ~/.clasprc.json
        run: |
          cat <<-EOS > ~/.clasprc.json
          {
            "token": {
              "access_token": "${{ secrets.ACCESS_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file openid https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/script.webapp.deploy",
              "token_type": "Bearer",
              "id_token": "${{ secrets.ID_TOKEN }}",
              "expiry_date": ${{ secrets.EXPIRY_DATE }},
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}"
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }
          EOS
      - name: Create .clasp.json
        run: |
          cat <<-EOS > $GITHUB_WORKSPACE/.clasp.json
          {
            "scriptId": "${{ secrets.SCRIPT_ID }}",
            "rootDir": "build"
          }
          EOS
      - run: yarn webpack
      - run: yarn clasp push --force
      - run: yarn clasp deploy -i ${{ secrets.DEPLOYMENT_ID }}
